apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: ${{"diebold/" + values.destination.repo}}
    sonarqube.org/project-key: ${{values.component_id}}
  tags:
    - recommended
    - java
    - rest
    - openapi
    - tpcloud
  links:
    - url: ${{"https://rancher.upco.cloud/dashboard/c/local/fleet/fleet.cattle.io.gitrepo/fleet-default/" + values.destination.repo}}
      title: Rancher
      icon: rancher
    - url: ${{"https://sonarqube.upco.cloud/dashboard?id=" + values.component_id}}
      title: SonarQube
      icon: sonarqube
    - url: ${{"https://jenkins.upco.cloud/job/diebold/job/" + values.destination.repo}}
      title: Jenkins
      icon: jenkins
spec:
  type: service
  owner: ${{values.owner | dump}}
  lifecycle: experimental
  system: tpcloud
  providesApis:
    - ${{values.component_id | dump}}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: ${{"diebold/" + values.destination.repo}}
    sonarqube.org/project-key: ${{values.component_id}}
  tags:
    - recommended
    - java
    - rest
    - openapi
    - tpcloud
  links:
    - url: ${{"https://rancher.upco.cloud/dashboard/c/local/fleet/fleet.cattle.io.gitrepo/fleet-default/" + values.destination.repo}}
      title: Rancher
      icon: rancher
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system: tpcloud
  definition: |
    openapi: 3.0.0
    info:
      title: Sample API
      description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
      version: 0.1.9
    servers:
      - url: http://api.example.com/v1
        description: Optional server description, e.g. Main (production) server
      - url: http://staging-api.example.com
        description: Optional server description, e.g. Internal staging server for testing
    paths:
      /users:
        get:
          summary: Returns a list of users.
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string