apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.component_id}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.component_id}}
  template:
    metadata:
      labels:
        app: ${{values.component_id}}
    spec:
      containers:
        - name: app
          image: "ghcr.io/diebold-xyz/${{values.component_id}}:latest"
          ports:
            - name: web
              containerPort: ${{values.http_port}}
      imagePullSecrets:
        - name: dockerconfigjson-github-com